name: Publish

on:
  push:
    branches:
      - main
      - master

jobs:
  ci:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Lint YAMLs
        run: npm run lint

      - name: Git configs
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Version
        run: npm version patch

      - name: Build
        run: npm run build

      - name: Test specs
        run: npm test

      - name: Upload to Cloudflare Pages
        run: |
          echo "<html><body>It works.</body></html>" > dist/index.html
          npx wrangler pages deploy dist --project-name="featurevisor-example-cloudflare"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Push back to origin
        run: |
          git add .featurevisor/*
          git commit --amend --no-edit
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
